### ISSUE TITLE
Domain name researchsoftware.org

### ISSUE THREAD

**Issue by benvanwerkhoven** [RSE-leaders/researchsoftware.org#1]
Setup the domain name researchsoftware.org to point to this site.

- [x] get the domain researchsoftware.org to point to http://rse-leaders.github.io/researchsoftware.org
- [x] create a file named CNAME with "researchsoftware.org"

**Comment by sdruskat** [comment]
Sitting next to @StephanJanosch on a train and he told me about the with/without dash thing at the intl meeting. Happy to forward research-software.org to researchsoftware.org if you like, at least for the time being. At the moment, there's https://cite.research-software.org under the domain only.

**Comment by shensicle** [comment]
Working now.

**Comment by alysbrett** [comment]
Thanks for getting this set up. I get an insecure connection error in Firefox though:

researchsoftware.org uses an invalid security certificate. The certificate is only valid for the following names: *.github.com, github.com, *.github.io, github.io Error code: SSL_ERROR_BAD_CERT_DOMAIN

**Comment by shensicle** [comment]
A discussion on this is in order. It turns out that GitHub does not support HTTPS for custom domains. It is on their internal feature list request system. So we could:

Leave this as-is: Not great
Redirect https://researchsoftware.org to http://researchsoftware.org: Also not great and will likely cause at least some users to receive a non-secure redirect warning
Encryption Service: Github suggested CloudFlare, but it's not officially supported and there appears to be a cost
Others: ??

**Comment by AlgyTaylor** [comment]
Probably will have worked this out already, but I imagine it's sending github's SSL certificate - so it's coming up as non-secure for the perfectly reasonable reason that the site (researchsoftware.org) isn't what it says it is (github.{com,io}).

I'd think redirecting it to the HTTP would be _less bad_ than leaving it _as_is_.  Both are insecure, the latter at least is _honest_ about it's lack of security rather than sending the wrong certificate so looking (potentially) malcious.

You could host it not-on github pages, e.g. with paid hosting (Hetzner Cloud is cheap, pretty decent & under EU/German data laws).   May be able to do it on something like Heroku or AWS for free given the low traffic.

Finally, you could find a friendly server to route the domain through (e.g. researchsoftware.org redirects to software.ac.uk, which in turn points it as the HTTPS site.  It makes software.ac.uk a 'man in the middle' as it were, so it's not perfectly 100% secure in the strictest sense, but it's probably 'good enough' since there's (presumably) no private, personal data on there.  You'd need a friendly webserver person, though.

**Comment by alysbrett** [comment]
Thank you both. As the proper support  is being rolled out already, perhaps redirecting https -> http or routing through another server would not be too bad. As mentioned, there is no personal data involved.

@markdturner - any comments on this? Is routing it through the rse.ac.uk webserver an interim option?

**Comment by alysbrett** [comment]
@shensicle @benvanwerkhoven @markdturner Can any of these interim options to work around the researchsoftware.org certificate issue be implemented easily/quickly?

Now some blog posts are being published and publicised I've had a response from a non-technical person I forwarded the link to that they "couldn't see it" and just got an error which is not the best look for us :-)

**Comment by benvanwerkhoven** [comment]
I can't find any resource that confirms that GitHub is currently rolling out HTTPS support for custom domains.

All solutions that I can find are using some other service in the middle, like CloudFlare. But @jameshclrk says he would vote against using that. I'm unsure why, it seems many people are using this.

I would be fine with redirecting https:// to http:// for the time being, if I knew how to do that. In the Settings panel, I only have the option to enforce https, not the other way around. Unchecking the box only enables http, it does not disable the malfunctioning https.

**Comment by shensicle** [comment]
I believe we can do that. Will have to check and make sure it doesn't violate our IT policies. Stand by.Scott


-------- Original Message --------
Subject: Re: [RSE-leaders/researchsoftware.org] Domain name
researchsoftware.org (#1)

**Comment by sdruskat** [comment]
Think you're sorted :).

https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by jameshclrk** [comment]
Because you've got a custom domain, *https*://rse-leaders.github.io/researchsoftware.org is being redirected to *http*://researchsoftware.org

You can fix it by using a relative path for the image, by using the custom domain or (maybe) by ticking the "Enforce HTTPS" box on the settings page.

**Comment by benvanwerkhoven** [comment]
Simply ticking the box enforce https did the trick. Thanks @jameshclrk !

**Comment by sdruskat** [comment]
Further to researchsoftware.org & research-software.org: 

Me and @alysbrett had a wee chat at RSE18 that the co-existence of the two domains is unfortunate. At the moment, the only real content at research-HYPHEN-software.org is https://cite.research-software.org (redirecting to *r-s.org/citation*), but there'll be more coming in the future. 

I don't know what you have planned in terms of subdomains, paths, etc., but I think me and Alys have agreed that r-HYPHEN-s.org root should redirect to rs.org root in any case.

As for existing content, I think the options are to use both domains interchangeably, so that r-HYPHEN-s/xxx redirects to rs/xxx (or the other way around), or that just r-HYPHEN-s redirects to rs and that's it. I'd be happy with either.

Let me know (or let's discuss) what you wanna do with this and I can start setting up the redirect.

**Comment by sdruskat** [comment]
Solved via a simple redirect straight to https://researchsoftware.org now that https is enforced.
